### ISSUE TITLE
Parameter --snap=1 does not work

### ISSUE THREAD

**Issue by ghost** [eps696/stylegan2ada#6]
Hello, thank you very much for the great repo.

For non-square experiments I use your repo with Google Colab (not Pro), here unfortunately the connection often breaks down unexpectedly, which is why I would like to change snaps from default=5 to 1. But I always get this error:

`/content/sg2-ada-pt-eps696/src
Traceback (most recent call last):
  File "train.py", line 406, in <module>
    main() # pylint: disable=no-value-for-parameter
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "train.py", line 353, in main
    run_desc, args = setup_training_loop_kwargs(**config_kwargs)
  File "train.py", line 61, in setup_training_loop_kwargs
    assert snap > 1, '--snap must be at least 1'
AssertionError: --snap must be at least 1`

I start my training with this command:

!python train.py \
--train_dir=/content/googledrive/MyDrive \
--data=/content/720x1280-Test.zip \
--cfg="eps" \
--mirror=True \
--snap=1 \
--seed=0 \
--kimg=25000 \
--aug=ada \
--target=0.699 \
--augpipe=bgc \
--gamma=6 \
--workers=2

**Comment by eps696** [comment]
thanks for reporting
reload repo and try again, should be ok now

**Comment by eps696** [comment]
i presume, the problem is solved. please reopen the issue, if it persists.
